### ISSUE TITLE
Deprecated variable "AnsibleUndefinedVariable: 'dict object' has no attribute 'ansible_eth1'"

### ISSUE THREAD

**Issue by ledroide** [adfinis-sygroup/mariadb-ansible-galera-cluster#1]
**ansible_eth1.ipv4** is deprecated. We should use **ansible_default_ipv4** instead.
I have fixed it in _roles/galera_conf/templates/server.cnf.j2_ and it works fine now : 
```
16c16
< {{ hostvars[host].ansible_eth1.ipv4.address }}
---
> {{ hostvars[host].ansible_default_ipv4.address }}
21c21
< wsrep_node_address={{ ansible_eth1.ipv4.address }}
---
> wsrep_node_address={{ ansible_default_ipv4.address }}
28c28
< wsrep_sst_receive_address={{ ansible_eth1.ipv4.address }}
---
> wsrep_sst_receive_address={{ ansible_default_ipv4.address }}
```
Pull request follows.
Regards,
Serge

**Comment by tongpu** [comment]
I can't find any information about the deprecation of the ansible_eth1 variable. Are you sure you've set up fact caching as described in [Prerequisites](https://github.com/adfinis-sygroup/mariadb-ansible-galera-cluster#prerequisites)?
