### ISSUE TITLE
vagrant test environment not working

### ISSUE THREAD

**Issue by dnl-jst** [adfinis-sygroup/mariadb-ansible-galera-cluster#4]
I tried to fire up the vagrant environment and run into a problem. When running the bootstrapping, the restart of the joiner nodes runs into a timeout. When looking into the logs of galera-db-2, I found the following error messages:

```
Feb 07 08:28:03 galera-db-2 mysqld[21769]: 2018-02-07  8:28:03 140223543498496 [ERROR] WSREP: Failed to read 'ready <addr>' from: wsrep_sst_xtrabackup-v2 --role 'joiner' --address '172.27.47.22...nt '21769'  ''
Feb 07 08:28:03 galera-db-2 mysqld[21769]: Read: '(null)'
Feb 07 08:28:03 galera-db-2 mysqld[21769]: 2018-02-07  8:28:03 140223543498496 [ERROR] WSREP: Process completed with error: wsrep_sst_xtrabackup-v2 --role 'joiner' --address '172.27.47.22' --da... (Broken pipe)
Feb 07 08:28:03 galera-db-2 mysqld[21769]: 2018-02-07  8:28:03 140223855065856 [ERROR] WSREP: Failed to prepare for 'xtrabackup-v2' SST. Unrecoverable.
Feb 07 08:28:03 galera-db-2 mysqld[21769]: 2018-02-07  8:28:03 140223855065856 [ERROR] Aborting
```

Seems to be a communication problem between the joiner node and the "master" or something?

Thank you!

**Comment by tongpu** [comment]
I was able to reproduce your issues, but it's currently not clear to me why this is happening. I'm going to update to MariaDB 10.2, because that fixes the issue.
