### ISSUE TITLE
xtrabackup-v2 timeout

### ISSUE THREAD

**Issue by rrouene** [adfinis-sygroup/mariadb-ansible-galera-cluster#7]
Issue when starting MariaDB on a node joining cluster:

> [Note] WSREP: Running: 'wsrep_sst_xtrabackup-v2 --role 'joiner' --address '192.168.0.94' --datadir '/var/lib/mysql/'   --parent '2040'  ''
> [Note] WSREP: (936558f8, 'tcp://0.0.0.0:4567') connection to peer 936558f8 with addr tcp://192.168.0.94:4567 timed out, no messages seen in PT3S

wsrep_sst_xtrabackup-v2 in timeout.

MariaDB version: 10.2.13 on CentOS 7

Solution:
http://lists.askmonty.org/pipermail/commits/2018-February/012037.html

You need to download:
https://jira.mariadb.org/secure/attachment/45259/45259_wsrep_sst_xtrabackup-v2.sh

and put it in /usr/bin/wsrep_sst_xtrabackup-v2

or:
> sed -i 's/LSOF_OUT=$(lsof -sTCP:LISTEN -i TCP:${PORT}.*/LSOF_OUT=$(lsof -sTCP:LISTEN -i TCP:${PORT} -a -c nc -c socat -F c 2> \/dev\/null || :)/' /usr/bin/wsrep_sst_xtrabackup-v2

**Comment by tongpu** [comment]
This is an error that needs to be fixed upstream and not within this demo playbook.

**Comment by tongpu** [comment]
@Sowappy MariaDB 10.2.14 has been released with the fix included.

**Comment by rrouene** [comment]
Ok thank you, I'll update.
