### ISSUE TITLE
AnsibleUndefinedVariable: 'ansible_eth1' is undefined

### ISSUE THREAD

**Issue by mgi2613github** [adfinis-sygroup/mariadb-ansible-galera-cluster#9]
root@vnf-01-vnf-00:/opt/vnfm/mariadb-ansible-galera-cluster-master# ansible --version
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

root@vnf-01-vnf-00:/opt/vnfm/mariadb-ansible-galera-cluster-master# ansible-playbook -i galera.hosts galera.yml --skip-tags setup -e "ansible_user=casa ansible_ssh_pass=casa ansible_sudo_pass=casa"

PLAY [galera_cluster] ***********************************************************************************************************************************************************************************

TASK [galera_privs : Ensure MariaDB is running] *********************************************************************************************************************************************************
ok: [s2dbarb]
ok: [s2db2]
ok: [s2db1]

TASK [galera_privs : Add Galera SST user] ***************************************************************************************************************************************************************
ok: [s2dbarb]
ok: [s2db1]
ok: [s2db2]

TASK [galera_conf : Add galera configuration] ***********************************************************************************************************************************************************
fatal: [s2db1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible_eth1' is undefined"}
fatal: [s2dbarb]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible_eth1' is undefined"}
fatal: [s2db2]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible_eth1' is undefined"}

PLAY RECAP **********************************************************************************************************************************************************************************************
s2db1                      : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
s2db2                      : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
s2dbarb                    : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

=============================================================
The file involved ansible_eth1 is /opt/vnfm/mariadb-ansible-galera-cluster-master/roles/galera_conf/templates
...
wsrep_node_address={{ ansible_eth1.ipv6.address }}
...
wsrep_sst_receive_address={{ ansible_eth1.ipv6.address }}
wsrep_sst_auth={{ galera_sst_user }}:{{ galera_sst_pass }}
....

By the way, where to set galera_sst_user, and set galera_sst_pass

Thank you so much.

Wei Yu

**Comment by tongpu** [comment]
I've fixed the hardcoded ansible_eth1 variable.

Regarding the `galera_sst_user` and `galera_sst_pass` variable I would recommend that you place it in the group vars of your cluster.
